import os
import re
from argparse import ArgumentParser
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Version:
    checksum: int
    ftOffset: int
    ftSize: int

VERSIONS = (
    Version(0, 0, 0),  # NTSC 1.0
    Version(0, 0xB91C, 0x6138),  # NTSC 1.1
    Version(0, 0xB8FC, 0) # PAL
    )

def createParser():
    parser = ArgumentParser()
    parser.add_argument("--executable", "-exe", help="Path to game's executable")
    parser.add_argument("--silentFile", "-fs", help="Path to game's SILENT. file")
    parser.add_argument("--filetableFile", "-ftb", help="Path to game's file table generated by SILENTASSETS.PY")
    parser.add_argument("--xmlFile", "-xml", help="Path to new .xml file for MKPSXISO")
    parser.add_argument("--buildFolder", "-b", help="Path to build folder")
    parser.add_argument("--outputFolder", "-o", help="Path to where the newly generated SILENT and executable file will be generated")
    return parser

def readTableLine(tableLine):
    tableData = []
    text = ""
    fileName = False
    i = 0
    for letter in tableLine:
        match letter:
            case '{' | ' ':
                continue
            case ',' | '\'' | '}':
                if i != 3:
                    tableData.append(int(text, 0))
                    text = ""
                    i += 1
                elif fileName == False:
                    tableData.append(text)
                    text = ""
                    i += 1
            case '(':
                text = ""
                fileName = True
            case ')':
                fileName = False
            case _:
                text += letter
            
    return tableData

def nameObfuscate(fileName):
    nameStr1 = ""
    nameStr2 = ""
    name1 = 0
    name2 = 0
    
    try:
        for letterIndex in range(0, 4):
            nameStr1 += fileName[letterIndex]
            
        for letterIndex in range(4, 8):
            nameStr2 += fileName[letterIndex]
    except:
        """did you know that the original script for
        Silent Hill: Revelation reveals *cough* that
        there was going to be a scene in the subways
        just like in the game however it was cut due
        budgets contraints"""
        
    for shift in range(4, 28, 6):
        letterIndex = (shift - 4) // 6
        if len(nameStr1) <= letterIndex:
            break
        if ord(nameStr1[letterIndex]) == 0:
            continue
        tempName = ord(nameStr1[letterIndex])
        tempName -= 32
        tempName &= 63
        tempName = tempName << shift
        name1 += tempName
    
    for shift in range(0, 24, 6):
        letterIndex = shift // 6
        if len(nameStr2) <= letterIndex:
            break
        if ord(nameStr2[letterIndex]) == 0:
            continue
        tempName = ord(nameStr2[letterIndex])
        tempName -= 32
        tempName &= 63
        tempName = tempName << shift
        name2 += tempName
    
    return name1, name2

# From SILENTASSETS.PY works for both encrypting and dencrypting overlays
def ovlEncryption(data):
    output = bytearray(data)
    outArray = memoryview(output).cast("I") # uint32_t
    seed = 0

    for i, value in enumerate(outArray):
        seed = (seed + 0x01309125) & 0xffffffff
        seed = (seed * 0x03a452f7) & 0xffffffff
        outArray[i] ^= seed

    return output

def main():
    # TODO: multiple version support
    version = VERSIONS[1]
    args = createParser().parse_args()
    
    fileTable = open(args.filetableFile)
    buildOvlPaths = [
    "/VIN/",
    "/1ST/"
    ]
    ovlNames = [
    "B_KONAMI",
    "BODYPROG",
    "STREAM",
    "STF_ROLL",
    "OPTION",
    "SAVELOAD",
    "MAP0_S00", "MAP0_S01", "MAP0_S02",
    "MAP1_S00", "MAP1_S01", "MAP1_S02", "MAP1_S03", "MAP1_S04", "MAP1_S05", "MAP1_S06",
    "MAP2_S00", "MAP2_S01", "MAP2_S02", "MAP2_S03", "MAP2_S04",
    "MAP3_S00", "MAP3_S01", "MAP3_S02", "MAP3_S03", "MAP3_S04", "MAP3_S05", "MAP3_S06",
    "MAP4_S00", "MAP4_S01", "MAP4_S02", "MAP4_S03", "MAP4_S04", "MAP4_S05", "MAP4_S06",
    "MAP5_S00", "MAP5_S01", "MAP5_S02", "MAP5_S03",
    "MAP6_S00", "MAP6_S01", "MAP6_S02", "MAP6_S03", "MAP6_S04", "MAP6_S05",
    "MAP7_S00", "MAP7_S01", "MAP7_S02", "MAP7_S03"
    ]
    
    
    
    #Get file information from the original file table
    #name, size, new size, value to rest/sum to the position and index
    fileTableNew = []
    fileTableOrig = []
    index = 0
        
    for x in fileTable:
        if x.strip().startswith("//"):  # Skip lines that start with "//"
            continue
        tableLine = readTableLine(re.findall(r"\{.*?\}", x)[0])
        
        fileTableOrig.append(tableLine)
        
        if tableLine[4] == 2:
            for ovl in ovlNames:
                if tableLine[3] == ovl:
                    if Path(f"{args.buildFolder}{buildOvlPaths[0]}{ovl}.BIN").is_file() or Path(f"{args.buildFolder}{buildOvlPaths[1]}{ovl}.BIN").is_file():
                        fileTableNew.append([ovl, tableLine[1], 0, 0, index])
        index += 1
    fileTable.close()
    
    if not fileTableOrig:
        print(fileTableOrig)
        print("No new overlay to insert")
        return
    
    # Re-lay out SILENT. sequentially. Every file keeps its original span (data plus any padding up
    # to the next file) unless a rebuilt overlay no longer fits, in which case the span grows to the
    # next sector boundary and every later file moves by the same number of sectors. HILL. follows
    # SILENT. on the disc, so its entries move by the total growth.
    SILENT_START = 64
    silentData = open(args.silentFile, "rb").read()
    silentEnd = SILENT_START + len(silentData) // 0x800

    def builtOverlay(entry):
        if entry[4] != 2 or entry[3] not in ovlNames:
            return None
        for path in buildOvlPaths:
            ovlPath = Path(f"{args.buildFolder}{path}{entry[3]}.BIN")
            if ovlPath.is_file():
                data = ovlPath.read_bytes()
                if entry[2] != 9:  # Only VIN/ overlays are stored unencrypted.
                    data = bytes(ovlEncryption(data))
                return data
        return None

    newSILENT = bytearray()
    cursor = SILENT_START
    silentEntries = [e for e in fileTableOrig if e[0] < silentEnd]
    for i, entry in enumerate(silentEntries):
        nextStart = silentEntries[i + 1][0] if i + 1 < len(silentEntries) else silentEnd
        span = silentData[(entry[0] - SILENT_START) * 0x800:(nextStart - SILENT_START) * 0x800]
        data = builtOverlay(entry)
        if data is not None:
            entry[1] = (len(data) + 0xFF) // 0x100  # Size in 256-byte blocks, rounded up.
            spanSize = max(len(span), (len(data) + 0x7FF) // 0x800 * 0x800)
            span = data + bytes(spanSize - len(data))
        entry[0] = cursor
        newSILENT += span
        cursor += len(span) // 0x800

    growth = cursor - silentEnd
    for entry in fileTableOrig[len(silentEntries):]:  # The table is in sector order.
        entry[0] += growth
    print(f"SILENT. grew by {growth} sectors")

    # Replace's exe file table
    EXE = open(args.executable, "rb")
    newEXE = open(args.outputFolder+"/USA/new_SLUS_007.07", "wb")
    EXENewData = bytearray()
    newEXE.write(EXE.read(version.ftOffset))
    EXE.seek(version.ftSize, 1)
    for tableLine in fileTableOrig:
        EXENewData += ((tableLine[1] << 19) + tableLine[0]).to_bytes(4, byteorder='little')
        EXENewData += (nameObfuscate(tableLine[3])[0] + tableLine[2]).to_bytes(4, byteorder='little')
        EXENewData += (nameObfuscate(tableLine[3])[1] + (tableLine[4] << 24)).to_bytes(4, byteorder='little')
    newEXE.write(EXENewData)
    newEXE.write(EXE.read())
    newEXE.close()
    EXE.close()

    with open(args.outputFolder+"/USA/new_SILENT.", "wb") as f:
        f.write(newSILENT)

    with open(args.xmlFile, "r") as XML:
        with open(os.path.dirname(args.xmlFile)+"/rebuild.xml", "a+") as newXML:
            newXML.truncate(0)
            for fileLine in XML:
                if "image_name=\"mkpsxiso.bin\"" in fileLine:
                    newXML.write(fileLine.replace("mkpsxiso", "build/SLUS_007.07"))
                elif "source=\"SLUS_007.07\"" in fileLine:
                    newXML.write(fileLine.replace("source=\"SLUS_007.07\"", "source=\"new_SLUS_007.07\""))
                elif "source=\"SILENT.\"" in fileLine:
                    newXML.write(fileLine.replace("source=\"SILENT.\"", "source=\"new_SILENT.\""))
                elif "source=\"SILENT\"" in fileLine:
                    newXML.write(fileLine.replace("source=\"SILENT\"", "source=\"new_SILENT\""))
                else:
                    newXML.write(fileLine)
    

if __name__ == "__main__":
    main()