#!/usr/bin/env python3
"""Generates lib_tests.h: the libgte/libkmath functions to test, with call stubs sized from their
prototypes. Pointer parameters point into the test arena (one 256-byte region each)."""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "port"))
import recomp  # noqa: E402  (prototype parser)

FUNCS = """ApplyMatrix ApplyMatrixLV ApplyMatrixSV ApplyRotMatrix ApplyRotMatrixLV CompMatrix LoadAverageCol Lzc
MulMatrix MulMatrix0 MulMatrix2 MulRotMatrix NormalColor NormalColor3 OuterProduct12 PushMatrix PopMatrix
ReadGeomOffset ReadGeomScreen ReadLightMatrix RotTrans RotTransPers RotTransPers3 RotTransPers4 ScaleMatrix
SetBackColor SetColorMatrix SetGeomOffset SetGeomScreen SetLightMatrix SetMulRotMatrix SetRotMatrix SetTransMatrix
Square0 SquareRoot0 SquareRoot12 TransMatrix TransposeMatrix VectorNormal ratan2
Math_Sin Math_Cos Math_RotMatrixZ Math_RotMatrixXyz Math_RotMatrixZxy Math_RotMatrixZxyNeg Math_RotMatrixXyzGte
Math_RotMatrixZxyNegGte""".split()

HEADERS = ["include/psyq/libgte.h", "include/bodyprog/math/math.h", "tools/port/recomp_protos.h"]


def params(name):
    """Returns (returns_pointer, returns_value, [is_pointer per param]) from the prototype text."""
    for h in HEADERS:
        text = re.sub(r"/\*.*?\*/", " ", open(os.path.join(ROOT, h)).read(), flags=re.S)
        m = re.search(r"(?:^|;|\})\s*(?:extern\s+)?([\w\s\*]*?)\b%s\s*\(([^;{}()]*)\)\s*;" % name, text, re.M)
        if m:
            ret, ps = m.group(1).strip(), m.group(2).strip()
            plist = [] if ps in ("", "void") else [p.strip() for p in ps.split(",")]
            return "*" in ret, ret != "void", ["*" in p or "[" in p for p in plist]
    sys.exit("no prototype for " + name)


lines = ["/* Generated by gen.py */", "#define LIB_TEST_NUM_FUNCS %d" % len(FUNCS)]
for f in FUNCS:
    lines.append("extern unsigned int %s();" % f)
lines.append("static const char* const lib_test_names[] = { %s };" % ", ".join('"%s"' % f for f in FUNCS))
flags = []
lines.append("static unsigned int lib_test_call(int f, const unsigned int* a)\n{\n    switch (f)\n    {")
for i, f in enumerate(FUNCS):
    rp, rv, ptrs = params(f)
    flags.append("%d" % ((1 if rv else 0) | (2 if rp else 0)))
    lines.append("        case %d: return %s(%s);" % (i, f, ", ".join("a[%d]" % k for k in range(len(ptrs)))))
lines.append("    }\n    return 0;\n}")
lines.append("/* bit 0: returns a value; bit 1: the value is a pointer (compared relative to the arena) */")
lines.append("static const unsigned char lib_test_ret[] = { %s };" % ", ".join(flags))
ptrmask = []
for f in FUNCS:
    _, _, ptrs = params(f)
    ptrmask.append("0x%X" % sum(1 << k for k, p in enumerate(ptrs) if p))
lines.append("/* bit k: parameter k is a pointer */")
lines.append("static const unsigned short lib_test_ptrs[] = { %s };" % ", ".join(ptrmask))
open(os.path.join(HERE, "lib_tests.h"), "w").write("\n".join(lines) + "\n")
print(len(FUNCS), "functions")
