#!/usr/bin/env python3
"""Generates the GTE test command list (cmds.h) and the PS1 command stubs (cmds.s).

Every opcode with every sf/lm combination, and MVMVA with every sf/mx/v/cv/lm combination.
"""
OPS = {  # name: opcode (bits 0-5) with the fake opcode bits Sony's tools use (bits 20-24)
    "RTPS": 0x0180001, "RTPT": 0x0280030, "NCLIP": 0x1400006, "OP": 0x170000C, "DPCS": 0x0780010,
    "INTPL": 0x0980011, "NCDS": 0x0E80413, "CDP": 0x1280414, "NCDT": 0x0F80416, "NCCS": 0x108041B,
    "CC": 0x138041C, "NCS": 0x0C8041E, "NCT": 0x0D80420, "SQR": 0x0A00428, "DCPL": 0x0680029,
    "DPCT": 0x0F8002A, "AVSZ3": 0x158002D, "AVSZ4": 0x168002E, "GPF": 0x190003D, "GPL": 0x1A0003E,
    "NCCT": 0x118043F,
}
cmds = []
for name, base in OPS.items():
    base &= ~((1 << 19) | (1 << 10))
    for sf in (0, 1):
        for lm in (0, 1):
            cmds.append((name, base | (sf << 19) | (lm << 10)))
for sf in (0, 1):
    for mx in range(4):
        for v in range(4):
            for cv in range(4):
                for lm in (0, 1):
                    cmds.append(("MVMVA", 0x0400012 | (sf << 19) | (mx << 17) | (v << 15) | (cv << 13) | (lm << 10)))

with open("cmds.h", "w") as f:
    f.write("/* Generated by gen.py */\n#define GTE_TEST_NUM_CMDS %d\n" % len(cmds))
    f.write("static const unsigned int gte_test_cmds[GTE_TEST_NUM_CMDS] = {\n")
    for name, c in cmds:
        f.write("    0x%07X, /* %s */\n" % (c, name))
    f.write("};\n")
with open("cmds.s", "w") as f:
    f.write("/* Generated by gen.py: one stub per command (COP2 immediates can't be computed at run time). */\n")
    f.write(".set noreorder\n.text\n")
    for i, (name, c) in enumerate(cmds):
        f.write("cmd_%d:\n    nop\n    nop\n    .word 0x%08X  /* cop2 %s */\n    nop\n    nop\n    jr $ra\n    nop\n" % (i, 0x4A000000 | c, name))
    f.write(".data\n.globl gte_test_stubs\ngte_test_stubs:\n")
    for i in range(len(cmds)):
        f.write("    .word cmd_%d\n" % i)
print(len(cmds), "commands")
