#!/usr/bin/env python3
"""Generates bridges for calls from recompiled code to plain C functions.

Recompiled code calls other functions as rc_<name>(RcRegs*). When <name> is itself recompiled, that
function exists; otherwise (libc, the HAL, game code) this writes a bridge rc_<name> that calls the C
function with the o32 arguments: a0-a3 plus 8 words from the stack at sp+16 (extra ones are ignored
by the callee). Result in v0.

    recomp_bridges.py <recomp_dir>      -> <recomp_dir>/bridge_<name>.c (one per function, so linking
                                           the recompiled code as an archive pulls in only what's used)
"""
import glob
import os
import re
import sys

d = sys.argv[1]
defined, used = set(), set()
for f in glob.glob(os.path.join(d, "*.c")):
    if os.path.basename(f).startswith("bridge_"):
        continue
    text = open(f).read()
    defined |= set(re.findall(r"^void rc_(\w+)\(RcRegs\* r\)\n\{", text, re.M))
    used |= set(re.findall(r"\brc_(\w+)\(r\);", text))
missing = sorted(used - defined)
for f in glob.glob(os.path.join(d, "bridge_*")):
    os.remove(f)
stk = ", ".join("RC_R32(r->r[29] + %d)" % (16 + 4 * i) for i in range(8))
for n in missing:
    open(os.path.join(d, "bridge_%s.c" % n), "w").write(
        "/* Generated by tools/port/recomp_bridges.py. Do not edit. */\n#include \"port/recomp.h\"\n"
        "extern unsigned int %s();\n"
        "void rc_%s(RcRegs* r) { r->r[2] = %s(r->r[4], r->r[5], r->r[6], r->r[7], %s); }\n" % (n, n, n, stk))
    open(os.path.join(d, "bridge_%s.data.s" % n), "w").write("")
print("%d bridges: %s" % (len(missing), " ".join(missing)))
