/* Generated by tools/port/gen_gte_inline.py from include/inline_no_dmpsx.h. Do not edit. */
#ifndef _PORT_GTE_FROM_INLINE_NO_DMPSX_H
#define _PORT_GTE_FROM_INLINE_NO_DMPSX_H

#include "port/gte.h"

#undef gte_rtps
#define gte_rtps() do { Gte_Command(0x0180001); } while (0)

#undef gte_rtpt
#define gte_rtpt() do { Gte_Command(0x0280030); } while (0)

#undef gte_rt
#define gte_rt() do { Gte_Command(0x0480012); } while (0)

#undef gte_rtv0
#define gte_rtv0() do { Gte_Command(0x0486012); } while (0)

#undef gte_rtv1
#define gte_rtv1() do { Gte_Command(0x048E012); } while (0)

#undef gte_rtv2
#define gte_rtv2() do { Gte_Command(0x0496012); } while (0)

#undef gte_rtir
#define gte_rtir() do { Gte_Command(0x049E012); } while (0)

#undef gte_rtir_sf0
#define gte_rtir_sf0() do { Gte_Command(0x041E012); } while (0)

#undef gte_rtv0tr
#define gte_rtv0tr() do { Gte_Command(0x0480012); } while (0)

#undef gte_rtv1tr
#define gte_rtv1tr() do { Gte_Command(0x0488012); } while (0)

#undef gte_rtv2tr
#define gte_rtv2tr() do { Gte_Command(0x0490012); } while (0)

#undef gte_rtirtr
#define gte_rtirtr() do { Gte_Command(0x0498012); } while (0)

#undef gte_rtv0bk
#define gte_rtv0bk() do { Gte_Command(0x0482012); } while (0)

#undef gte_rtv1bk
#define gte_rtv1bk() do { Gte_Command(0x048A012); } while (0)

#undef gte_rtv2bk
#define gte_rtv2bk() do { Gte_Command(0x0492012); } while (0)

#undef gte_rtirbk
#define gte_rtirbk() do { Gte_Command(0x049A012); } while (0)

#undef gte_ll
#define gte_ll() do { Gte_Command(0x04A6412); } while (0)

#undef gte_llv0
#define gte_llv0() do { Gte_Command(0x04A6012); } while (0)

#undef gte_llv1
#define gte_llv1() do { Gte_Command(0x04AE012); } while (0)

#undef gte_llv2
#define gte_llv2() do { Gte_Command(0x04B6012); } while (0)

#undef gte_llir
#define gte_llir() do { Gte_Command(0x04BE012); } while (0)

#undef gte_llv0tr
#define gte_llv0tr() do { Gte_Command(0x04A0012); } while (0)

#undef gte_llv1tr
#define gte_llv1tr() do { Gte_Command(0x04A8012); } while (0)

#undef gte_llv2tr
#define gte_llv2tr() do { Gte_Command(0x04B0012); } while (0)

#undef gte_llirtr
#define gte_llirtr() do { Gte_Command(0x04B8012); } while (0)

#undef gte_llv0bk
#define gte_llv0bk() do { Gte_Command(0x04A2012); } while (0)

#undef gte_llv1bk
#define gte_llv1bk() do { Gte_Command(0x04AA012); } while (0)

#undef gte_llv2bk
#define gte_llv2bk() do { Gte_Command(0x04B2012); } while (0)

#undef gte_llirbk
#define gte_llirbk() do { Gte_Command(0x04BA012); } while (0)

#undef gte_lc
#define gte_lc() do { Gte_Command(0x04DA412); } while (0)

#undef gte_lcv0
#define gte_lcv0() do { Gte_Command(0x04C6012); } while (0)

#undef gte_lcv1
#define gte_lcv1() do { Gte_Command(0x04CE012); } while (0)

#undef gte_lcv2
#define gte_lcv2() do { Gte_Command(0x04D6012); } while (0)

#undef gte_lcir
#define gte_lcir() do { Gte_Command(0x04DE012); } while (0)

#undef gte_lcv0tr
#define gte_lcv0tr() do { Gte_Command(0x04C0012); } while (0)

#undef gte_lcv1tr
#define gte_lcv1tr() do { Gte_Command(0x04C8012); } while (0)

#undef gte_lcv2tr
#define gte_lcv2tr() do { Gte_Command(0x04D0012); } while (0)

#undef gte_lcirtr
#define gte_lcirtr() do { Gte_Command(0x04D8012); } while (0)

#undef gte_lcv0bk
#define gte_lcv0bk() do { Gte_Command(0x04C2012); } while (0)

#undef gte_lcv1bk
#define gte_lcv1bk() do { Gte_Command(0x04CA012); } while (0)

#undef gte_lcv2bk
#define gte_lcv2bk() do { Gte_Command(0x04D2012); } while (0)

#undef gte_lcirbk
#define gte_lcirbk() do { Gte_Command(0x04DA012); } while (0)

#undef gte_dpcl
#define gte_dpcl() do { Gte_Command(0x0680029); } while (0)

#undef gte_dpcs
#define gte_dpcs() do { Gte_Command(0x0780010); } while (0)

#undef gte_dpct
#define gte_dpct() do { Gte_Command(0x0F8002A); } while (0)

#undef gte_intpl
#define gte_intpl() do { Gte_Command(0x0980011); } while (0)

#undef gte_sqr12
#define gte_sqr12() do { Gte_Command(0x0A80428); } while (0)

#undef gte_sqr0
#define gte_sqr0() do { Gte_Command(0x0A00428); } while (0)

#undef gte_ncs
#define gte_ncs() do { Gte_Command(0x0C8041E); } while (0)

#undef gte_nct
#define gte_nct() do { Gte_Command(0x0D80420); } while (0)

#undef gte_ncds
#define gte_ncds() do { Gte_Command(0x0E80413); } while (0)

#undef gte_ncdt
#define gte_ncdt() do { Gte_Command(0x0F80416); } while (0)

#undef gte_nccs
#define gte_nccs() do { Gte_Command(0x108041B); } while (0)

#undef gte_ncct
#define gte_ncct() do { Gte_Command(0x118043F); } while (0)

#undef gte_cdp
#define gte_cdp() do { Gte_Command(0x1280414); } while (0)

#undef gte_cc
#define gte_cc() do { Gte_Command(0x138041C); } while (0)

#undef gte_nclip
#define gte_nclip() do { Gte_Command(0x1400006); } while (0)

#undef gte_avsz3
#define gte_avsz3() do { Gte_Command(0x158002D); } while (0)

#undef gte_avsz4
#define gte_avsz4() do { Gte_Command(0x168002E); } while (0)

#undef gte_op12
#define gte_op12() do { Gte_Command(0x178000C); } while (0)

#undef gte_op0
#define gte_op0() do { Gte_Command(0x170000C); } while (0)

#undef gte_gpf12
#define gte_gpf12() do { Gte_Command(0x198003D); } while (0)

#undef gte_gpf0
#define gte_gpf0() do { Gte_Command(0x190003D); } while (0)

#undef gte_gpl12
#define gte_gpl12() do { Gte_Command(0x1A8003E); } while (0)

#undef gte_gpl0
#define gte_gpl0() do { Gte_Command(0x1A0003E); } while (0)

#endif
