/* Generated by tools/port/gen_gte_inline.py from include/gpu.h. Do not edit. */
#ifndef _PORT_GTE_FROM_GPU_H
#define _PORT_GTE_FROM_GPU_H

#include "port/gte.h"

#undef gte_lddqa
#define gte_lddqa(r0) do { Gte_CtrlWrite(27, (unsigned int)(r0)); } while (0)

#undef gte_lddqb_0
#define gte_lddqb_0() do { Gte_CtrlWrite(28, (unsigned int)0u); } while (0)

#undef gte_ldtr_0
#define gte_ldtr_0() do { Gte_CtrlWrite(5, (unsigned int)0u); Gte_CtrlWrite(6, (unsigned int)0u); Gte_CtrlWrite(7, (unsigned int)0u); } while (0)

#undef gte_SetLightSVector
#define gte_SetLightSVector(p) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((p)) + (0)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((p)) + (4)); Gte_CtrlWrite(8, (unsigned int)_r12); Gte_CtrlWrite(9, (unsigned int)_r13); Gte_CtrlWrite(10, (unsigned int)0u); Gte_CtrlWrite(11, (unsigned int)0u); Gte_CtrlWrite(12, (unsigned int)0u); } while (0);

#undef gte_ldsv_
#define gte_ldsv_(val) do { Gte_DataWrite(9, (unsigned int)(val)); Gte_DataWrite(10, (unsigned int)(val)); Gte_DataWrite(11, (unsigned int)(val)); } while (0);

#undef gte_stIR1
#define gte_stIR1() ({ u32 __r; do { (__r) = Gte_DataRead(9); } while (0); __r; })

#undef gte_SetVector0
#define gte_SetVector0(p) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((p)) + (0)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((p)) + (4)); Gte_DataWrite(0, (unsigned int)_r12); Gte_DataWrite(1, (unsigned int)_r13); } while (0)

#undef gte_SetLightSourceXY
#define gte_SetLightSourceXY(x, y) do { unsigned int _in0 = (unsigned int)(x); unsigned int _in1 = (unsigned int)(y); _in0 = _in0 << 16; _in0 = _in0 >> 16; _in1 = _in1 << 16; _in0 = _in0 | _in1; Gte_CtrlWrite(8, (unsigned int)_in0); } while (0)

#undef gte_SetLightSourceZ
#define gte_SetLightSourceZ(z) do { Gte_CtrlWrite(9, (unsigned int)((z) & 0xFFFF)); Gte_CtrlWrite(10, (unsigned int)0u); Gte_CtrlWrite(11, (unsigned int)0u); Gte_CtrlWrite(12, (unsigned int)0u); } while (0)

#undef gte_SetRotMatrix_Row0_1
#define gte_SetRotMatrix_Row0_1(r0) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(0, (unsigned int)_r12); _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (8)); Gte_CtrlWrite(1, (unsigned int)_r13); Gte_CtrlWrite(2, (unsigned int)_r12); } while (0)

#undef gte_SetRotMatrix_Row2
#define gte_SetRotMatrix_Row2(r0) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (12)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (16)); Gte_CtrlWrite(3, (unsigned int)_r12); Gte_CtrlWrite(4, (unsigned int)_r13); } while (0)

#undef gte_LoadVector0_1_2_XYZ
#define gte_LoadVector0_1_2_XYZ(xy, z) do { unsigned int _r12; _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((z)) + (0)); Gte_DataWrite(0, *(unsigned int*)((unsigned char*)((xy)) + (0))); Gte_DataWrite(1, (unsigned int)_r12); _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((z)) + (2)); Gte_DataWrite(2, *(unsigned int*)((unsigned char*)((xy)) + (4))); Gte_DataWrite(3, (unsigned int)_r12); _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((z)) + (4)); Gte_DataWrite(4, *(unsigned int*)((unsigned char*)((xy)) + (8))); Gte_DataWrite(5, (unsigned int)_r12); } while (0)

#undef gte_FetchScreen0_1_2_XYZ
#define gte_FetchScreen0_1_2_XYZ(xy, z) do { unsigned int _r12; _r12 = Gte_DataRead(17); *(unsigned int*)((unsigned char*)((xy)) + (0)) = Gte_DataRead(12); *(unsigned short*)((unsigned char*)((z)) + (0)) = (unsigned short)_r12; _r12 = Gte_DataRead(18); *(unsigned int*)((unsigned char*)((xy)) + (4)) = Gte_DataRead(13); *(unsigned short*)((unsigned char*)((z)) + (2)) = (unsigned short)_r12; _r12 = Gte_DataRead(19); *(unsigned int*)((unsigned char*)((xy)) + (8)) = Gte_DataRead(14); *(unsigned short*)((unsigned char*)((z)) + (4)) = (unsigned short)_r12; } while (0)

#undef gte_SetRotMatrix_custom
#define gte_SetRotMatrix_custom(mat) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (16)); Gte_CtrlWrite(4, (unsigned int)_r12); _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (10)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (4)); _r12 = _r12 << 16; _r12 = _r12 + _r13; Gte_CtrlWrite(3, (unsigned int)_r12); _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (14)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (8)); _r12 = _r12 << 16; _r12 = _r12 + _r13; Gte_CtrlWrite(2, (unsigned int)_r12); _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (2)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (12)); _r12 = _r12 << 16; _r12 = _r12 + _r13; Gte_CtrlWrite(1, (unsigned int)_r12); _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (6)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((mat)) + (0)); _r12 = _r12 << 16; _r12 = _r12 + _r13; Gte_CtrlWrite(0, (unsigned int)_r12); } while (0)

#undef gte_LoadVector0_XYZ
#define gte_LoadVector0_XYZ(x, y, z) do { unsigned int _in0 = (unsigned int)(x); unsigned int _in1 = (unsigned int)(y); _in0 = _in0 << 16; _in0 = _in0 >> 16; _in1 = _in1 << 16; _in0 = _in0 | _in1; Gte_DataWrite(0, (unsigned int)_in0); Gte_DataWrite(1, (unsigned int)(z)); } while (0)

#undef gte_ldvxy0_Zero
#define gte_ldvxy0_Zero() do { Gte_DataWrite(0, (unsigned int)0u); } while (0)

#undef gte_ldvxy0
#define gte_ldvxy0(val) do { Gte_DataWrite(0, (unsigned int)(val)); } while (0)

#undef gte_ldvz0
#define gte_ldvz0() do { Gte_DataWrite(1, (unsigned int)0u); } while (0)

#undef gte_stSZ3
#define gte_stSZ3() ({ u32 __r; do { (__r) = Gte_DataRead(19); } while (0); __r; })

#undef gte_stMAC0
#define gte_stMAC0() ({ s32 __r; do { (__r) = Gte_DataRead(24); } while (0); __r; })

#undef gte_stMAC1
#define gte_stMAC1() ({ u32 __r; do { (__r) = Gte_DataRead(25); } while (0); __r; })

#undef gte_stMAC2
#define gte_stMAC2() ({ u32 __r; do { (__r) = Gte_DataRead(26); } while (0); __r; })

#undef gte_stMAC12
#define gte_stMAC12(r0) do { unsigned int _r12, _r13; _r12 = Gte_DataRead(25); *(unsigned short*)((unsigned char*)((r0)) + (0)) = (unsigned short)_r12; _r13 = Gte_DataRead(26); *(unsigned short*)((unsigned char*)((r0)) + (2)) = (unsigned short)_r13; } while (0)

#undef gte_ldsv3_
#define gte_ldsv3_(x, y, z) do { Gte_DataWrite(9, (unsigned int)(x)); Gte_DataWrite(10, (unsigned int)(y)); Gte_DataWrite(11, (unsigned int)(z)); } while (0)

#undef gte_ldR13R21
#define gte_ldR13R21(val) do { unsigned int _r12; _r12 = (val) | 0u; _r12 = 0u - _r12; Gte_CtrlWrite(1, (unsigned int)_r12); } while (0)

#undef gte_ldR11R12
#define gte_ldR11R12(r0) do { Gte_CtrlWrite(0, (unsigned int)(r0)); Gte_CtrlWrite(2, (unsigned int)(r0)); } while (0)

#undef gte_IsDisabled
#define gte_IsDisabled() ({ u32 __r; do { (__r) = 0u; } while (0); __r; })

#undef gte_stlzcr
#define gte_stlzcr(dst) do { (dst) = Gte_DataRead(31); } while (0)

#undef gte_ldir_stbk
#define gte_ldir_stbk() do { unsigned int _r12; _r12 = Gte_CtrlRead(13); Gte_DataWrite(9, (unsigned int)_r12); _r12 = Gte_CtrlRead(14); Gte_DataWrite(10, (unsigned int)_r12); _r12 = Gte_CtrlRead(15); Gte_DataWrite(11, (unsigned int)_r12); } while (0)

#undef gte_ldmac_stir
#define gte_ldmac_stir() do { unsigned int _r12; _r12 = Gte_DataRead(25); Gte_CtrlWrite(13, (unsigned int)_r12); _r12 = Gte_DataRead(26); Gte_CtrlWrite(14, (unsigned int)_r12); _r12 = Gte_DataRead(27); Gte_CtrlWrite(15, (unsigned int)_r12); } while (0)

#endif
