/* Generated by tools/port/gen_gte_inline.py from include/psyq/inline_c.h. Do not edit. */
#ifndef _PORT_GTE_FROM_INLINE_C_H
#define _PORT_GTE_FROM_INLINE_C_H

#include "port/gte.h"

#undef gte_ldv0
#define gte_ldv0( r0 ) do { Gte_DataWrite(0, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(1, *(unsigned int*)((unsigned char*)((r0)) + (4))); } while (0)

#undef gte_ldv1
#define gte_ldv1( r0 ) do { Gte_DataWrite(2, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(3, *(unsigned int*)((unsigned char*)((r0)) + (4))); } while (0)

#undef gte_ldv2
#define gte_ldv2( r0 ) do { Gte_DataWrite(4, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(5, *(unsigned int*)((unsigned char*)((r0)) + (4))); } while (0)

#undef gte_ldv3
#define gte_ldv3( r0, r1, r2 ) do { Gte_DataWrite(0, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(1, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(2, *(unsigned int*)((unsigned char*)((r1)) + (0))); Gte_DataWrite(3, *(unsigned int*)((unsigned char*)((r1)) + (4))); Gte_DataWrite(4, *(unsigned int*)((unsigned char*)((r2)) + (0))); Gte_DataWrite(5, *(unsigned int*)((unsigned char*)((r2)) + (4))); } while (0)

#undef gte_ldv3c
#define gte_ldv3c( r0 ) do { Gte_DataWrite(0, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(1, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(2, *(unsigned int*)((unsigned char*)((r0)) + (8))); Gte_DataWrite(3, *(unsigned int*)((unsigned char*)((r0)) + (12))); Gte_DataWrite(4, *(unsigned int*)((unsigned char*)((r0)) + (16))); Gte_DataWrite(5, *(unsigned int*)((unsigned char*)((r0)) + (20))); } while (0)

#undef gte_ldv3c_vertc
#define gte_ldv3c_vertc( r0 ) do { Gte_DataWrite(0, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(1, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(2, *(unsigned int*)((unsigned char*)((r0)) + (12))); Gte_DataWrite(3, *(unsigned int*)((unsigned char*)((r0)) + (16))); Gte_DataWrite(4, *(unsigned int*)((unsigned char*)((r0)) + (24))); Gte_DataWrite(5, *(unsigned int*)((unsigned char*)((r0)) + (28))); } while (0)

#undef gte_ldv01
#define gte_ldv01( r0, r1 ) do { Gte_DataWrite(0, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(1, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(2, *(unsigned int*)((unsigned char*)((r1)) + (0))); Gte_DataWrite(3, *(unsigned int*)((unsigned char*)((r1)) + (4))); } while (0)

#undef gte_ldv01c
#define gte_ldv01c( r0 ) do { Gte_DataWrite(0, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(1, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(2, *(unsigned int*)((unsigned char*)((r0)) + (8))); Gte_DataWrite(3, *(unsigned int*)((unsigned char*)((r0)) + (12))); } while (0)

#undef gte_ldrgb
#define gte_ldrgb( r0 ) do { Gte_DataWrite(6, *(unsigned int*)((unsigned char*)((r0)) + (0))); } while (0)

#undef gte_ldrgb3
#define gte_ldrgb3( r0, r1, r2 ) do { Gte_DataWrite(20, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(21, *(unsigned int*)((unsigned char*)((r1)) + (0))); Gte_DataWrite(22, *(unsigned int*)((unsigned char*)((r2)) + (0))); Gte_DataWrite(6, *(unsigned int*)((unsigned char*)((r2)) + (0))); } while (0)

#undef gte_ldrgb3c
#define gte_ldrgb3c( r0 ) do { Gte_DataWrite(20, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(21, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(22, *(unsigned int*)((unsigned char*)((r0)) + (8))); Gte_DataWrite(6, *(unsigned int*)((unsigned char*)((r0)) + (8))); } while (0)

#undef gte_ldlv0
#define gte_ldlv0( r0 ) do { unsigned int _r12, _r13; _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (4)); _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (0)); _r13 = _r13 << 16; _r12 = _r12 | _r13; Gte_DataWrite(0, (unsigned int)_r12); Gte_DataWrite(1, *(unsigned int*)((unsigned char*)((r0)) + (8))); } while (0)

#undef gte_ldlvl
#define gte_ldlvl( r0 ) do { Gte_DataWrite(9, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(10, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(11, *(unsigned int*)((unsigned char*)((r0)) + (8))); } while (0)

#undef gte_ldsv
#define gte_ldsv( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (2)); _r14 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (4)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); Gte_DataWrite(11, (unsigned int)_r14); } while (0)

#undef gte_ldbv
#define gte_ldbv( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (1)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); } while (0)

#undef gte_ldcv
#define gte_ldcv( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (1)); _r14 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (2)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); Gte_DataWrite(11, (unsigned int)_r14); } while (0)

#undef gte_ldclmv
#define gte_ldclmv( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (6)); _r14 = (unsigned int)*(unsigned short*)((unsigned char*)((r0)) + (12)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); Gte_DataWrite(11, (unsigned int)_r14); } while (0)

#undef gte_lddp
#define gte_lddp( r0 ) do { Gte_DataWrite(8, (unsigned int)(r0)); } while (0)

#undef gte_ldsxy0
#define gte_ldsxy0( r0 ) do { Gte_DataWrite(12, (unsigned int)(r0)); } while (0)

#undef gte_ldsxy1
#define gte_ldsxy1( r0 ) do { Gte_DataWrite(13, (unsigned int)(r0)); } while (0)

#undef gte_ldsxy2
#define gte_ldsxy2( r0 ) do { Gte_DataWrite(14, (unsigned int)(r0)); } while (0)

#undef gte_ldsxy3
#define gte_ldsxy3( r0, r1, r2 ) do { Gte_DataWrite(12, (unsigned int)(r0)); Gte_DataWrite(14, (unsigned int)(r2)); Gte_DataWrite(13, (unsigned int)(r1)); } while (0)

#undef gte_ldsxy3c
#define gte_ldsxy3c( r0 ) do { Gte_DataWrite(12, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(13, *(unsigned int*)((unsigned char*)((r0)) + (4))); Gte_DataWrite(14, *(unsigned int*)((unsigned char*)((r0)) + (8))); } while (0)

#undef gte_ldsz3
#define gte_ldsz3( r0, r1, r2 ) do { Gte_DataWrite(17, (unsigned int)(r0)); Gte_DataWrite(18, (unsigned int)(r1)); Gte_DataWrite(19, (unsigned int)(r2)); } while (0)

#undef gte_ldsz4
#define gte_ldsz4( r0, r1, r2, r3 ) do { Gte_DataWrite(16, (unsigned int)(r0)); Gte_DataWrite(17, (unsigned int)(r1)); Gte_DataWrite(18, (unsigned int)(r2)); Gte_DataWrite(19, (unsigned int)(r3)); } while (0)

#undef gte_ldopv1
#define gte_ldopv1( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(0, (unsigned int)_r12); _r14 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (8)); Gte_CtrlWrite(2, (unsigned int)_r13); Gte_CtrlWrite(4, (unsigned int)_r14); } while (0)

#undef gte_ldopv2
#define gte_ldopv2( r0 ) do { Gte_DataWrite(11, *(unsigned int*)((unsigned char*)((r0)) + (8))); Gte_DataWrite(9, *(unsigned int*)((unsigned char*)((r0)) + (0))); Gte_DataWrite(10, *(unsigned int*)((unsigned char*)((r0)) + (4))); } while (0)

#undef gte_ldlzc
#define gte_ldlzc( r0 ) do { Gte_DataWrite(30, (unsigned int)(r0)); } while (0)

#undef gte_SetRGBcd
#define gte_SetRGBcd( r0 ) do { Gte_DataWrite(6, *(unsigned int*)((unsigned char*)((r0)) + (0))); } while (0)

#undef gte_ldbkdir
#define gte_ldbkdir( r0, r1, r2 ) do { Gte_CtrlWrite(13, (unsigned int)(r0)); Gte_CtrlWrite(14, (unsigned int)(r1)); Gte_CtrlWrite(15, (unsigned int)(r2)); } while (0)

#undef gte_SetBackColor
#define gte_SetBackColor( r0, r1, r2 ) do { unsigned int _r12, _r13, _r14; _r12 = (r0) << 4; _r13 = (r1) << 4; _r14 = (r2) << 4; Gte_CtrlWrite(13, (unsigned int)_r12); Gte_CtrlWrite(14, (unsigned int)_r13); Gte_CtrlWrite(15, (unsigned int)_r14); } while (0)

#undef gte_ldfcdir
#define gte_ldfcdir( r0, r1, r2 ) do { Gte_CtrlWrite(21, (unsigned int)(r0)); Gte_CtrlWrite(22, (unsigned int)(r1)); Gte_CtrlWrite(23, (unsigned int)(r2)); } while (0)

#undef gte_SetFarColor
#define gte_SetFarColor( r0, r1, r2 ) do { unsigned int _r12, _r13, _r14; _r12 = (r0) << 4; _r13 = (r1) << 4; _r14 = (r2) << 4; Gte_CtrlWrite(21, (unsigned int)_r12); Gte_CtrlWrite(22, (unsigned int)_r13); Gte_CtrlWrite(23, (unsigned int)_r14); } while (0)

#undef gte_SetGeomOffset
#define gte_SetGeomOffset( r0, r1 ) do { unsigned int _r12, _r13; _r12 = (r0) << 16; _r13 = (r1) << 16; Gte_CtrlWrite(24, (unsigned int)_r12); Gte_CtrlWrite(25, (unsigned int)_r13); } while (0)

#undef gte_SetGeomScreen
#define gte_SetGeomScreen( r0 ) do { Gte_CtrlWrite(26, (unsigned int)(r0)); } while (0)

#undef gte_ldsvrtrow0
#define gte_ldsvrtrow0( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(0, (unsigned int)_r12); Gte_CtrlWrite(1, (unsigned int)_r13); } while (0)

#undef gte_SetRotMatrix
#define gte_SetRotMatrix( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(0, (unsigned int)_r12); Gte_CtrlWrite(1, (unsigned int)_r13); _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (8)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (12)); _r14 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (16)); Gte_CtrlWrite(2, (unsigned int)_r12); Gte_CtrlWrite(3, (unsigned int)_r13); Gte_CtrlWrite(4, (unsigned int)_r14); } while (0)

#undef gte_ldsvllrow0
#define gte_ldsvllrow0( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(8, (unsigned int)_r12); Gte_CtrlWrite(9, (unsigned int)_r13); } while (0)

#undef gte_SetLightMatrix
#define gte_SetLightMatrix( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(8, (unsigned int)_r12); Gte_CtrlWrite(9, (unsigned int)_r13); _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (8)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (12)); _r14 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (16)); Gte_CtrlWrite(10, (unsigned int)_r12); Gte_CtrlWrite(11, (unsigned int)_r13); Gte_CtrlWrite(12, (unsigned int)_r14); } while (0)

#undef gte_ldsvlcrow0
#define gte_ldsvlcrow0( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(16, (unsigned int)_r12); Gte_CtrlWrite(17, (unsigned int)_r13); } while (0)

#undef gte_SetColorMatrix
#define gte_SetColorMatrix( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(16, (unsigned int)_r12); Gte_CtrlWrite(17, (unsigned int)_r13); _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (8)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (12)); _r14 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (16)); Gte_CtrlWrite(18, (unsigned int)_r12); Gte_CtrlWrite(19, (unsigned int)_r13); Gte_CtrlWrite(20, (unsigned int)_r14); } while (0)

#undef gte_SetTransMatrix
#define gte_SetTransMatrix( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (20)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (24)); Gte_CtrlWrite(5, (unsigned int)_r12); _r14 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (28)); Gte_CtrlWrite(6, (unsigned int)_r13); Gte_CtrlWrite(7, (unsigned int)_r14); } while (0)

#undef gte_ldtr
#define gte_ldtr( r0, r1, r2 ) do { Gte_CtrlWrite(5, (unsigned int)(r0)); Gte_CtrlWrite(6, (unsigned int)(r1)); Gte_CtrlWrite(7, (unsigned int)(r2)); } while (0)

#undef gte_SetTransVector
#define gte_SetTransVector( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); _r14 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (8)); Gte_CtrlWrite(5, (unsigned int)_r12); Gte_CtrlWrite(6, (unsigned int)_r13); Gte_CtrlWrite(7, (unsigned int)_r14); } while (0)

#undef gte_ld_intpol_uv0
#define gte_ld_intpol_uv0( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (1)); Gte_CtrlWrite(21, (unsigned int)_r12); Gte_CtrlWrite(22, (unsigned int)_r13); } while (0)

#undef gte_ld_intpol_uv1
#define gte_ld_intpol_uv1( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (1)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); } while (0)

#undef gte_ld_intpol_bv0
#define gte_ld_intpol_bv0( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (1)); Gte_CtrlWrite(21, (unsigned int)_r12); Gte_CtrlWrite(22, (unsigned int)_r13); } while (0)

#undef gte_ld_intpol_bv1
#define gte_ld_intpol_bv1( r0 ) do { unsigned int _r12, _r13; _r12 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned char*)((unsigned char*)((r0)) + (1)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); } while (0)

#undef gte_ld_intpol_sv0
#define gte_ld_intpol_sv0( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(short*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(short*)((unsigned char*)((r0)) + (2)); _r14 = (unsigned int)*(short*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(21, (unsigned int)_r12); Gte_CtrlWrite(22, (unsigned int)_r13); Gte_CtrlWrite(23, (unsigned int)_r14); } while (0)

#undef gte_ld_intpol_sv1
#define gte_ld_intpol_sv1( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(short*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(short*)((unsigned char*)((r0)) + (2)); _r14 = (unsigned int)*(short*)((unsigned char*)((r0)) + (4)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); Gte_DataWrite(11, (unsigned int)_r14); } while (0)

#undef gte_ldfc
#define gte_ldfc( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (4)); _r14 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (8)); Gte_CtrlWrite(21, (unsigned int)_r12); Gte_CtrlWrite(22, (unsigned int)_r13); Gte_CtrlWrite(23, (unsigned int)_r14); } while (0)

#undef gte_ldopv2SV
#define gte_ldopv2SV( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(short*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(short*)((unsigned char*)((r0)) + (2)); _r14 = (unsigned int)*(short*)((unsigned char*)((r0)) + (4)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); Gte_DataWrite(11, (unsigned int)_r14); } while (0)

#undef gte_ldopv1SV
#define gte_ldopv1SV( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = (unsigned int)*(short*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(short*)((unsigned char*)((r0)) + (2)); Gte_CtrlWrite(0, (unsigned int)_r12); _r14 = (unsigned int)*(short*)((unsigned char*)((r0)) + (4)); Gte_CtrlWrite(2, (unsigned int)_r13); Gte_CtrlWrite(4, (unsigned int)_r14); } while (0)

#undef gte_rtps
#define gte_rtps() __gte_untranslatable_gte_rtps()

#undef gte_rtpt
#define gte_rtpt() __gte_untranslatable_gte_rtpt()

#undef gte_rt
#define gte_rt() __gte_untranslatable_gte_rt()

#undef gte_rtv0
#define gte_rtv0() __gte_untranslatable_gte_rtv0()

#undef gte_rtv1
#define gte_rtv1() __gte_untranslatable_gte_rtv1()

#undef gte_rtv2
#define gte_rtv2() __gte_untranslatable_gte_rtv2()

#undef gte_rtir
#define gte_rtir() __gte_untranslatable_gte_rtir()

#undef gte_rtir_sf0
#define gte_rtir_sf0() __gte_untranslatable_gte_rtir_sf0()

#undef gte_rtv0tr
#define gte_rtv0tr() __gte_untranslatable_gte_rtv0tr()

#undef gte_rtv1tr
#define gte_rtv1tr() __gte_untranslatable_gte_rtv1tr()

#undef gte_rtv2tr
#define gte_rtv2tr() __gte_untranslatable_gte_rtv2tr()

#undef gte_rtirtr
#define gte_rtirtr() __gte_untranslatable_gte_rtirtr()

#undef gte_rtv0bk
#define gte_rtv0bk() __gte_untranslatable_gte_rtv0bk()

#undef gte_rtv1bk
#define gte_rtv1bk() __gte_untranslatable_gte_rtv1bk()

#undef gte_rtv2bk
#define gte_rtv2bk() __gte_untranslatable_gte_rtv2bk()

#undef gte_rtirbk
#define gte_rtirbk() __gte_untranslatable_gte_rtirbk()

#undef gte_ll
#define gte_ll() __gte_untranslatable_gte_ll()

#undef gte_llv0
#define gte_llv0() __gte_untranslatable_gte_llv0()

#undef gte_llv1
#define gte_llv1() __gte_untranslatable_gte_llv1()

#undef gte_llv2
#define gte_llv2() __gte_untranslatable_gte_llv2()

#undef gte_llir
#define gte_llir() __gte_untranslatable_gte_llir()

#undef gte_llv0tr
#define gte_llv0tr() __gte_untranslatable_gte_llv0tr()

#undef gte_llv1tr
#define gte_llv1tr() __gte_untranslatable_gte_llv1tr()

#undef gte_llv2tr
#define gte_llv2tr() __gte_untranslatable_gte_llv2tr()

#undef gte_llirtr
#define gte_llirtr() __gte_untranslatable_gte_llirtr()

#undef gte_llv0bk
#define gte_llv0bk() __gte_untranslatable_gte_llv0bk()

#undef gte_llv1bk
#define gte_llv1bk() __gte_untranslatable_gte_llv1bk()

#undef gte_llv2bk
#define gte_llv2bk() __gte_untranslatable_gte_llv2bk()

#undef gte_llirbk
#define gte_llirbk() __gte_untranslatable_gte_llirbk()

#undef gte_lc
#define gte_lc() __gte_untranslatable_gte_lc()

#undef gte_lcv0
#define gte_lcv0() __gte_untranslatable_gte_lcv0()

#undef gte_lcv1
#define gte_lcv1() __gte_untranslatable_gte_lcv1()

#undef gte_lcv2
#define gte_lcv2() __gte_untranslatable_gte_lcv2()

#undef gte_lcir
#define gte_lcir() __gte_untranslatable_gte_lcir()

#undef gte_lcv0tr
#define gte_lcv0tr() __gte_untranslatable_gte_lcv0tr()

#undef gte_lcv1tr
#define gte_lcv1tr() __gte_untranslatable_gte_lcv1tr()

#undef gte_lcv2tr
#define gte_lcv2tr() __gte_untranslatable_gte_lcv2tr()

#undef gte_lcirtr
#define gte_lcirtr() __gte_untranslatable_gte_lcirtr()

#undef gte_lcv0bk
#define gte_lcv0bk() __gte_untranslatable_gte_lcv0bk()

#undef gte_lcv1bk
#define gte_lcv1bk() __gte_untranslatable_gte_lcv1bk()

#undef gte_lcv2bk
#define gte_lcv2bk() __gte_untranslatable_gte_lcv2bk()

#undef gte_lcirbk
#define gte_lcirbk() __gte_untranslatable_gte_lcirbk()

#undef gte_dpcl
#define gte_dpcl() __gte_untranslatable_gte_dpcl()

#undef gte_dpcs
#define gte_dpcs() __gte_untranslatable_gte_dpcs()

#undef gte_dpct
#define gte_dpct() __gte_untranslatable_gte_dpct()

#undef gte_intpl
#define gte_intpl() __gte_untranslatable_gte_intpl()

#undef gte_sqr12
#define gte_sqr12() __gte_untranslatable_gte_sqr12()

#undef gte_sqr0
#define gte_sqr0() __gte_untranslatable_gte_sqr0()

#undef gte_ncs
#define gte_ncs() __gte_untranslatable_gte_ncs()

#undef gte_nct
#define gte_nct() __gte_untranslatable_gte_nct()

#undef gte_ncds
#define gte_ncds() __gte_untranslatable_gte_ncds()

#undef gte_ncdt
#define gte_ncdt() __gte_untranslatable_gte_ncdt()

#undef gte_nccs
#define gte_nccs() __gte_untranslatable_gte_nccs()

#undef gte_ncct
#define gte_ncct() __gte_untranslatable_gte_ncct()

#undef gte_cdp
#define gte_cdp() __gte_untranslatable_gte_cdp()

#undef gte_cc
#define gte_cc() __gte_untranslatable_gte_cc()

#undef gte_nclip
#define gte_nclip() __gte_untranslatable_gte_nclip()

#undef gte_avsz3
#define gte_avsz3() __gte_untranslatable_gte_avsz3()

#undef gte_avsz4
#define gte_avsz4() __gte_untranslatable_gte_avsz4()

#undef gte_op12
#define gte_op12() __gte_untranslatable_gte_op12()

#undef gte_op0
#define gte_op0() __gte_untranslatable_gte_op0()

#undef gte_gpf12
#define gte_gpf12() __gte_untranslatable_gte_gpf12()

#undef gte_gpf0
#define gte_gpf0() __gte_untranslatable_gte_gpf0()

#undef gte_gpl12
#define gte_gpl12() __gte_untranslatable_gte_gpl12()

#undef gte_gpl0
#define gte_gpl0() __gte_untranslatable_gte_gpl0()

#undef gte_mvmva_core
#define gte_mvmva_core( r0 ) __gte_untranslatable_gte_mvmva_core()

#undef gte_rtps_b
#define gte_rtps_b() __gte_untranslatable_gte_rtps_b()

#undef gte_rtpt_b
#define gte_rtpt_b() __gte_untranslatable_gte_rtpt_b()

#undef gte_rt_b
#define gte_rt_b() __gte_untranslatable_gte_rt_b()

#undef gte_rtv0_b
#define gte_rtv0_b() __gte_untranslatable_gte_rtv0_b()

#undef gte_rtv1_b
#define gte_rtv1_b() __gte_untranslatable_gte_rtv1_b()

#undef gte_rtv2_b
#define gte_rtv2_b() __gte_untranslatable_gte_rtv2_b()

#undef gte_rtir_b
#define gte_rtir_b() __gte_untranslatable_gte_rtir_b()

#undef gte_rtir_sf0_b
#define gte_rtir_sf0_b() __gte_untranslatable_gte_rtir_sf0_b()

#undef gte_rtv0tr_b
#define gte_rtv0tr_b() __gte_untranslatable_gte_rtv0tr_b()

#undef gte_rtv1tr_b
#define gte_rtv1tr_b() __gte_untranslatable_gte_rtv1tr_b()

#undef gte_rtv2tr_b
#define gte_rtv2tr_b() __gte_untranslatable_gte_rtv2tr_b()

#undef gte_rtirtr_b
#define gte_rtirtr_b() __gte_untranslatable_gte_rtirtr_b()

#undef gte_rtv0bk_b
#define gte_rtv0bk_b() __gte_untranslatable_gte_rtv0bk_b()

#undef gte_rtv1bk_b
#define gte_rtv1bk_b() __gte_untranslatable_gte_rtv1bk_b()

#undef gte_rtv2bk_b
#define gte_rtv2bk_b() __gte_untranslatable_gte_rtv2bk_b()

#undef gte_rtirbk_b
#define gte_rtirbk_b() __gte_untranslatable_gte_rtirbk_b()

#undef gte_ll_b
#define gte_ll_b() __gte_untranslatable_gte_ll_b()

#undef gte_llv0_b
#define gte_llv0_b() __gte_untranslatable_gte_llv0_b()

#undef gte_llv1_b
#define gte_llv1_b() __gte_untranslatable_gte_llv1_b()

#undef gte_llv2_b
#define gte_llv2_b() __gte_untranslatable_gte_llv2_b()

#undef gte_llir_b
#define gte_llir_b() __gte_untranslatable_gte_llir_b()

#undef gte_llv0tr_b
#define gte_llv0tr_b() __gte_untranslatable_gte_llv0tr_b()

#undef gte_llv1tr_b
#define gte_llv1tr_b() __gte_untranslatable_gte_llv1tr_b()

#undef gte_llv2tr_b
#define gte_llv2tr_b() __gte_untranslatable_gte_llv2tr_b()

#undef gte_llirtr_b
#define gte_llirtr_b() __gte_untranslatable_gte_llirtr_b()

#undef gte_llv0bk_b
#define gte_llv0bk_b() __gte_untranslatable_gte_llv0bk_b()

#undef gte_llv1bk_b
#define gte_llv1bk_b() __gte_untranslatable_gte_llv1bk_b()

#undef gte_llv2bk_b
#define gte_llv2bk_b() __gte_untranslatable_gte_llv2bk_b()

#undef gte_llirbk_b
#define gte_llirbk_b() __gte_untranslatable_gte_llirbk_b()

#undef gte_lc_b
#define gte_lc_b() __gte_untranslatable_gte_lc_b()

#undef gte_lcv0_b
#define gte_lcv0_b() __gte_untranslatable_gte_lcv0_b()

#undef gte_lcv1_b
#define gte_lcv1_b() __gte_untranslatable_gte_lcv1_b()

#undef gte_lcv2_b
#define gte_lcv2_b() __gte_untranslatable_gte_lcv2_b()

#undef gte_lcir_b
#define gte_lcir_b() __gte_untranslatable_gte_lcir_b()

#undef gte_lcv0tr_b
#define gte_lcv0tr_b() __gte_untranslatable_gte_lcv0tr_b()

#undef gte_lcv1tr_b
#define gte_lcv1tr_b() __gte_untranslatable_gte_lcv1tr_b()

#undef gte_lcv2tr_b
#define gte_lcv2tr_b() __gte_untranslatable_gte_lcv2tr_b()

#undef gte_lcirtr_b
#define gte_lcirtr_b() __gte_untranslatable_gte_lcirtr_b()

#undef gte_lcv0bk_b
#define gte_lcv0bk_b() __gte_untranslatable_gte_lcv0bk_b()

#undef gte_lcv1bk_b
#define gte_lcv1bk_b() __gte_untranslatable_gte_lcv1bk_b()

#undef gte_lcv2bk_b
#define gte_lcv2bk_b() __gte_untranslatable_gte_lcv2bk_b()

#undef gte_lcirbk_b
#define gte_lcirbk_b() __gte_untranslatable_gte_lcirbk_b()

#undef gte_dpcl_b
#define gte_dpcl_b() __gte_untranslatable_gte_dpcl_b()

#undef gte_dpcs_b
#define gte_dpcs_b() __gte_untranslatable_gte_dpcs_b()

#undef gte_dpct_b
#define gte_dpct_b() __gte_untranslatable_gte_dpct_b()

#undef gte_intpl_b
#define gte_intpl_b() __gte_untranslatable_gte_intpl_b()

#undef gte_sqr12_b
#define gte_sqr12_b() __gte_untranslatable_gte_sqr12_b()

#undef gte_sqr0_b
#define gte_sqr0_b() __gte_untranslatable_gte_sqr0_b()

#undef gte_ncs_b
#define gte_ncs_b() __gte_untranslatable_gte_ncs_b()

#undef gte_nct_b
#define gte_nct_b() __gte_untranslatable_gte_nct_b()

#undef gte_ncds_b
#define gte_ncds_b() __gte_untranslatable_gte_ncds_b()

#undef gte_ncdt_b
#define gte_ncdt_b() __gte_untranslatable_gte_ncdt_b()

#undef gte_nccs_b
#define gte_nccs_b() __gte_untranslatable_gte_nccs_b()

#undef gte_ncct_b
#define gte_ncct_b() __gte_untranslatable_gte_ncct_b()

#undef gte_cdp_b
#define gte_cdp_b() __gte_untranslatable_gte_cdp_b()

#undef gte_cc_b
#define gte_cc_b() __gte_untranslatable_gte_cc_b()

#undef gte_nclip_b
#define gte_nclip_b() __gte_untranslatable_gte_nclip_b()

#undef gte_avsz3_b
#define gte_avsz3_b() __gte_untranslatable_gte_avsz3_b()

#undef gte_avsz4_b
#define gte_avsz4_b() __gte_untranslatable_gte_avsz4_b()

#undef gte_op12_b
#define gte_op12_b() __gte_untranslatable_gte_op12_b()

#undef gte_op0_b
#define gte_op0_b() __gte_untranslatable_gte_op0_b()

#undef gte_gpf12_b
#define gte_gpf12_b() __gte_untranslatable_gte_gpf12_b()

#undef gte_gpf0_b
#define gte_gpf0_b() __gte_untranslatable_gte_gpf0_b()

#undef gte_gpl12_b
#define gte_gpl12_b() __gte_untranslatable_gte_gpl12_b()

#undef gte_gpl0_b
#define gte_gpl0_b() __gte_untranslatable_gte_gpl0_b()

#undef gte_mvmva_core_b
#define gte_mvmva_core_b( r0 ) __gte_untranslatable_gte_mvmva_core_b()

#undef gte_stsxy
#define gte_stsxy( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3
#define gte_stsxy3( r0, r1, r2 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r1)) + (0)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r2)) + (0)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3c
#define gte_stsxy3c( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy2
#define gte_stsxy2( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy1
#define gte_stsxy1( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(13); } while (0)

#undef gte_stsxy0
#define gte_stsxy0( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(12); } while (0)

#undef gte_stsxy01
#define gte_stsxy01( r0, r1 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r1)) + (0)) = Gte_DataRead(13); } while (0)

#undef gte_stsxy01c
#define gte_stsxy01c( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(13); } while (0)

#undef gte_stsxy3_f3
#define gte_stsxy3_f3( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (12)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3_g3
#define gte_stsxy3_g3( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (24)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3_ft3
#define gte_stsxy3_ft3( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (24)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3_gt3
#define gte_stsxy3_gt3( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (20)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (32)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3_f4
#define gte_stsxy3_f4( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (12)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3_g4
#define gte_stsxy3_g4( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (24)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3_ft4
#define gte_stsxy3_ft4( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (24)) = Gte_DataRead(14); } while (0)

#undef gte_stsxy3_gt4
#define gte_stsxy3_gt4( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(12); *(unsigned int*)((unsigned char*)((r0)) + (20)) = Gte_DataRead(13); *(unsigned int*)((unsigned char*)((r0)) + (32)) = Gte_DataRead(14); } while (0)

#undef gte_stdp
#define gte_stdp( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(8); } while (0)

#undef gte_stflg
#define gte_stflg( r0 ) do { unsigned int _r12; _r12 = Gte_CtrlRead(31); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; } while (0)

#undef gte_stflg_4
#define gte_stflg_4( r0 ) do { unsigned int _r12, _r13; _r12 = Gte_CtrlRead(31); _r13 = 0u + (unsigned int)(4); _r13 = _r13 << 16; _r12 = _r12 & _r13; *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; } while (0)

#undef gte_stsz
#define gte_stsz( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(19); } while (0)

#undef gte_stsz3
#define gte_stsz3( r0, r1, r2 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(17); *(unsigned int*)((unsigned char*)((r1)) + (0)) = Gte_DataRead(18); *(unsigned int*)((unsigned char*)((r2)) + (0)) = Gte_DataRead(19); } while (0)

#undef gte_stsz4
#define gte_stsz4( r0, r1, r2, r3 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(16); *(unsigned int*)((unsigned char*)((r1)) + (0)) = Gte_DataRead(17); *(unsigned int*)((unsigned char*)((r2)) + (0)) = Gte_DataRead(18); *(unsigned int*)((unsigned char*)((r3)) + (0)) = Gte_DataRead(19); } while (0)

#undef gte_stsz3c
#define gte_stsz3c( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(17); *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(18); *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(19); } while (0)

#undef gte_stsz4c
#define gte_stsz4c( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(16); *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(17); *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(18); *(unsigned int*)((unsigned char*)((r0)) + (12)) = Gte_DataRead(19); } while (0)

#undef gte_stszotz
#define gte_stszotz( r0 ) do { unsigned int _r12; _r12 = Gte_DataRead(19); _r12 = (unsigned int)((int)_r12 >> 2); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; } while (0)

#undef gte_stotz
#define gte_stotz( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(7); } while (0)

#undef gte_stopz
#define gte_stopz( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(24); } while (0)

#undef gte_stlvl
#define gte_stlvl( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(9); *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(10); *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(11); } while (0)

#undef gte_stlvnl
#define gte_stlvnl( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(25); *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(26); *(unsigned int*)((unsigned char*)((r0)) + (8)) = Gte_DataRead(27); } while (0)

#undef gte_stlvnl0
#define gte_stlvnl0( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(25); } while (0)

#undef gte_stlvnl1
#define gte_stlvnl1( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(26); } while (0)

#undef gte_stlvnl2
#define gte_stlvnl2( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(27); } while (0)

#undef gte_stsv
#define gte_stsv( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); _r14 = Gte_DataRead(11); *(unsigned short*)((unsigned char*)((r0)) + (0)) = (unsigned short)_r12; *(unsigned short*)((unsigned char*)((r0)) + (2)) = (unsigned short)_r13; *(unsigned short*)((unsigned char*)((r0)) + (4)) = (unsigned short)_r14; } while (0)

#undef gte_stclmv
#define gte_stclmv( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); _r14 = Gte_DataRead(11); *(unsigned short*)((unsigned char*)((r0)) + (0)) = (unsigned short)_r12; *(unsigned short*)((unsigned char*)((r0)) + (6)) = (unsigned short)_r13; *(unsigned short*)((unsigned char*)((r0)) + (12)) = (unsigned short)_r14; } while (0)

#undef gte_stbv
#define gte_stbv( r0 ) do { unsigned int _r12, _r13; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); *(unsigned char*)((unsigned char*)((r0)) + (0)) = (unsigned char)_r12; *(unsigned char*)((unsigned char*)((r0)) + (1)) = (unsigned char)_r13; } while (0)

#undef gte_stcv
#define gte_stcv( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); _r14 = Gte_DataRead(11); *(unsigned char*)((unsigned char*)((r0)) + (0)) = (unsigned char)_r12; *(unsigned char*)((unsigned char*)((r0)) + (1)) = (unsigned char)_r13; *(unsigned char*)((unsigned char*)((r0)) + (2)) = (unsigned char)_r14; } while (0)

#undef gte_strgb
#define gte_strgb( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(22); } while (0)

#undef gte_strgb3
#define gte_strgb3( r0, r1, r2 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(20); *(unsigned int*)((unsigned char*)((r1)) + (0)) = Gte_DataRead(21); *(unsigned int*)((unsigned char*)((r2)) + (0)) = Gte_DataRead(22); } while (0)

#undef gte_strgb3_g3
#define gte_strgb3_g3( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(20); *(unsigned int*)((unsigned char*)((r0)) + (12)) = Gte_DataRead(21); *(unsigned int*)((unsigned char*)((r0)) + (20)) = Gte_DataRead(22); } while (0)

#undef gte_strgb3_gt3
#define gte_strgb3_gt3( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(20); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(21); *(unsigned int*)((unsigned char*)((r0)) + (28)) = Gte_DataRead(22); } while (0)

#undef gte_strgb3_g4
#define gte_strgb3_g4( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(20); *(unsigned int*)((unsigned char*)((r0)) + (12)) = Gte_DataRead(21); *(unsigned int*)((unsigned char*)((r0)) + (20)) = Gte_DataRead(22); } while (0)

#undef gte_strgb3_gt4
#define gte_strgb3_gt4( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (4)) = Gte_DataRead(20); *(unsigned int*)((unsigned char*)((r0)) + (16)) = Gte_DataRead(21); *(unsigned int*)((unsigned char*)((r0)) + (28)) = Gte_DataRead(22); } while (0)

#undef gte_ReadGeomOffset
#define gte_ReadGeomOffset( r0, r1 ) do { unsigned int _r12, _r13; _r12 = Gte_CtrlRead(24); _r13 = Gte_CtrlRead(25); _r12 = (unsigned int)((int)_r12 >> 16); _r13 = (unsigned int)((int)_r13 >> 16); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r1)) + (0)) = (unsigned int)_r13; } while (0)

#undef gte_ReadGeomScreen
#define gte_ReadGeomScreen( r0 ) do { unsigned int _r12; _r12 = Gte_CtrlRead(26); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; } while (0)

#undef gte_ReadRotMatrix
#define gte_ReadRotMatrix( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_CtrlRead(0); _r13 = Gte_CtrlRead(1); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (4)) = (unsigned int)_r13; _r12 = Gte_CtrlRead(2); _r13 = Gte_CtrlRead(3); _r14 = Gte_CtrlRead(4); *(unsigned int*)((unsigned char*)((r0)) + (8)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (12)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (16)) = (unsigned int)_r14; _r12 = Gte_CtrlRead(5); _r13 = Gte_CtrlRead(6); _r14 = Gte_CtrlRead(7); *(unsigned int*)((unsigned char*)((r0)) + (20)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (24)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (28)) = (unsigned int)_r14; } while (0)

#undef gte_sttr
#define gte_sttr( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_CtrlRead(5); _r13 = Gte_CtrlRead(6); _r14 = Gte_CtrlRead(7); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (4)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (8)) = (unsigned int)_r14; } while (0)

#undef gte_ReadLightMatrix
#define gte_ReadLightMatrix( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_CtrlRead(8); _r13 = Gte_CtrlRead(9); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (4)) = (unsigned int)_r13; _r12 = Gte_CtrlRead(10); _r13 = Gte_CtrlRead(11); _r14 = Gte_CtrlRead(12); *(unsigned int*)((unsigned char*)((r0)) + (8)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (12)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (16)) = (unsigned int)_r14; _r12 = Gte_CtrlRead(13); _r13 = Gte_CtrlRead(14); _r14 = Gte_CtrlRead(15); *(unsigned int*)((unsigned char*)((r0)) + (20)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (24)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (28)) = (unsigned int)_r14; } while (0)

#undef gte_ReadColorMatrix
#define gte_ReadColorMatrix( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_CtrlRead(16); _r13 = Gte_CtrlRead(17); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (4)) = (unsigned int)_r13; _r12 = Gte_CtrlRead(18); _r13 = Gte_CtrlRead(19); _r14 = Gte_CtrlRead(20); *(unsigned int*)((unsigned char*)((r0)) + (8)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (12)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (16)) = (unsigned int)_r14; _r12 = Gte_CtrlRead(21); _r13 = Gte_CtrlRead(22); _r14 = Gte_CtrlRead(23); *(unsigned int*)((unsigned char*)((r0)) + (20)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (24)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (28)) = (unsigned int)_r14; } while (0)

#undef gte_stlzc
#define gte_stlzc( r0 ) do { *(unsigned int*)((unsigned char*)((r0)) + (0)) = Gte_DataRead(31); } while (0)

#undef gte_stfc
#define gte_stfc( r0 ) do { unsigned int _r12, _r13, _r14; _r12 = Gte_CtrlRead(21); _r13 = Gte_CtrlRead(22); _r14 = Gte_CtrlRead(23); *(unsigned int*)((unsigned char*)((r0)) + (0)) = (unsigned int)_r12; *(unsigned int*)((unsigned char*)((r0)) + (4)) = (unsigned int)_r13; *(unsigned int*)((unsigned char*)((r0)) + (8)) = (unsigned int)_r14; } while (0)

#undef gte_mvlvtr
#define gte_mvlvtr() do { unsigned int _r12, _r13, _r14; _r12 = Gte_DataRead(25); _r13 = Gte_DataRead(26); _r14 = Gte_DataRead(27); Gte_CtrlWrite(5, (unsigned int)_r12); Gte_CtrlWrite(6, (unsigned int)_r13); Gte_CtrlWrite(7, (unsigned int)_r14); } while (0)

#undef gte_nop
#define gte_nop() do {  } while (0)

#undef gte_subdvl
#define gte_subdvl( r0, r1, r2 ) do { unsigned int _r12, _r13, _r15; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r1)) + (0)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); _r12 = (unsigned int)((int)_r12 >> 16); _r13 = (unsigned int)((int)_r13 >> 16); _r15 = _r12 - _r13; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); *(unsigned int*)((unsigned char*)((r2)) + (4)) = (unsigned int)_r15; _r12 = _r12 - _r13; *(unsigned int*)((unsigned char*)((r2)) + (0)) = (unsigned int)_r12; } while (0)

#undef gte_subdvd
#define gte_subdvd( r0, r1, r2 ) do { unsigned int _r12, _r13, _r15; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r1)) + (0)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); _r12 = (unsigned int)((int)_r12 >> 16); _r13 = (unsigned int)((int)_r13 >> 16); _r15 = _r12 - _r13; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); *(unsigned short*)((unsigned char*)((r2)) + (2)) = (unsigned short)_r15; _r12 = _r12 - _r13; *(unsigned short*)((unsigned char*)((r2)) + (0)) = (unsigned short)_r12; } while (0)

#undef gte_adddvl
#define gte_adddvl( r0, r1, r2 ) do { unsigned int _r12, _r13, _r15; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r1)) + (0)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); _r12 = (unsigned int)((int)_r12 >> 16); _r13 = (unsigned int)((int)_r13 >> 16); _r15 = _r12 + _r13; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); *(unsigned int*)((unsigned char*)((r2)) + (4)) = (unsigned int)_r15; _r12 = _r12 + _r13; *(unsigned int*)((unsigned char*)((r2)) + (0)) = (unsigned int)_r12; } while (0)

#undef gte_adddvd
#define gte_adddvd( r0, r1, r2 ) do { unsigned int _r12, _r13, _r15; _r12 = (unsigned int)*(unsigned int*)((unsigned char*)((r0)) + (0)); _r13 = (unsigned int)*(unsigned int*)((unsigned char*)((r1)) + (0)); Gte_DataWrite(9, (unsigned int)_r12); Gte_DataWrite(10, (unsigned int)_r13); _r12 = (unsigned int)((int)_r12 >> 16); _r13 = (unsigned int)((int)_r13 >> 16); _r15 = _r12 + _r13; _r12 = Gte_DataRead(9); _r13 = Gte_DataRead(10); *(unsigned short*)((unsigned char*)((r2)) + (2)) = (unsigned short)_r15; _r12 = _r12 + _r13; *(unsigned short*)((unsigned char*)((r2)) + (0)) = (unsigned short)_r12; } while (0)

#undef gte_FlipRotMatrixX
#define gte_FlipRotMatrixX() do { unsigned int _r12, _r13, _r14, _r15; _r12 = Gte_CtrlRead(0); _r13 = Gte_CtrlRead(1); _r14 = _r12 << 16; _r14 = (unsigned int)((int)_r14 >> 16); _r14 = 0u - _r14; _r15 = (unsigned int)((int)_r12 >> 16); _r15 = 0u - _r15; _r15 = _r15 << 16; _r14 = _r14 << 16; _r14 = _r14 >> 16; _r14 = _r14 | _r15; Gte_CtrlWrite(0, (unsigned int)_r14); _r14 = _r13 << 16; _r14 = (unsigned int)((int)_r14 >> 16); _r14 = 0u - _r14; _r15 = (unsigned int)((int)_r13 >> 16); _r15 = _r15 << 16; _r14 = _r14 << 16; _r14 = _r14 >> 16; _r14 = _r14 | _r15; Gte_CtrlWrite(1, (unsigned int)_r14); } while (0)

#undef gte_FlipTRX
#define gte_FlipTRX() do { unsigned int _r12; _r12 = Gte_CtrlRead(5); _r12 = 0u - _r12; Gte_CtrlWrite(5, (unsigned int)_r12); } while (0)

#endif
