#ifndef _PORT_OVERLAY_H
#define _PORT_OVERLAY_H

/** @brief Port overlays (src/port/overlay.c): every overlay is linked in, so loading one again must
 * reset its variables, as reading its file from disc does on the PS1. */

typedef struct
{
    int         fileIdx; /* file whose read loads this overlay */
    const char* name;
    char*       dataStart;
    char*       dataEnd;
    char*       bssStart;
    char*       bssEnd;
} Port_OverlayRange;

/* Generated by tools/port/port_link.py (build/port/overlay_ranges.c). */
extern const Port_OverlayRange g_PortOverlayRanges[];
extern const int               g_PortOverlayRangeCount;

/** Saves every overlay's initial .data (call once, before any overlay runs). */
void Port_OverlaySnapshot(void);

#endif
