#ifndef _PORT_RECOMP_H
#define _PORT_RECOMP_H

#include "port/prof.h"

/** @brief Runtime support for C generated by tools/port/recomp.py from PS1 (MIPS-I) object code.
 *
 * Recompiled functions share a register file; a wrapper with the original C name sets it up for each
 * call from game code. Addresses are plain 32-bit values: valid on the EE, whose pointers are 32-bit.
 * Port build only (`SH_PORT`). Plain C types: the port compiles with `-nostdinc`.
 */

#include "port/gte.h"

typedef struct
{
    unsigned int r[32];
    unsigned int hi;
    unsigned int lo;
} RcRegs;

#define RC_STACK_WORDS 1024 /* Emulated stack per outermost call (4 KiB). */

#define RC_R8(a)  (*(signed char*)(unsigned long)(a))
#define RC_RU8(a) (*(unsigned char*)(unsigned long)(a))
#define RC_R16(a) (*(short*)(unsigned long)(a))
#define RC_RU16(a) (*(unsigned short*)(unsigned long)(a))
#define RC_R32(a) (*(unsigned int*)(unsigned long)(a))

/** Code addresses in recompiled data (jump tables etc.) are stored as this marker plus the offset into
 * the object's .text, since recompiled code has no PS1 addresses. */
#define RC_TEXT_MARK 0xC0DE0000u

/** Called when recompiled code jumps through a register to an address that isn't a known jump-table
 * target (port bug or corrupted data). Defined in src/port/recomp_rt.c. */
void Rc_BadJump(unsigned int target);

/** Unaligned loads/stores (lwl/lwr/swl/swr), little-endian MIPS semantics. */
static inline unsigned int Rc_Lwl(unsigned int rt, unsigned int addr)
{
    unsigned int sh = addr & 3, w = RC_R32(addr & ~3u);
    return (rt & (0x00FFFFFFu >> (sh * 8))) | (w << (24 - sh * 8));
}
static inline unsigned int Rc_Lwr(unsigned int rt, unsigned int addr)
{
    unsigned int sh = addr & 3, w = RC_R32(addr & ~3u);
    return (rt & ~(0xFFFFFFFFu >> (sh * 8))) | (w >> (sh * 8));
}
static inline void Rc_Swl(unsigned int rt, unsigned int addr)
{
    unsigned int sh = addr & 3, a = addr & ~3u, w = RC_R32(a);
    RC_R32(a) = (w & (0xFFFFFF00u << (sh * 8))) | (rt >> (24 - sh * 8));
}
static inline void Rc_Swr(unsigned int rt, unsigned int addr)
{
    unsigned int sh = addr & 3, a = addr & ~3u, w = RC_R32(a);
    RC_R32(a) = (w & (0x00FFFFFFu >> (24 - sh * 8))) | (rt << (sh * 8));
}

/** MIPS DIV/DIVU, including the hardware's results for division by zero and 0x80000000 / -1. */
static inline void Rc_Div(RcRegs* r, unsigned int a, unsigned int b)
{
    int n = (int)a, d = (int)b;
    if (d == 0)
    {
        r->hi = a;
        r->lo = n < 0 ? 1u : 0xFFFFFFFFu;
    }
    else if (a == 0x80000000u && d == -1)
    {
        r->hi = 0;
        r->lo = 0x80000000u;
    }
    else
    {
        r->hi = (unsigned int)(n % d);
        r->lo = (unsigned int)(n / d);
    }
}
static inline void Rc_Divu(RcRegs* r, unsigned int a, unsigned int b)
{
    if (b == 0)
    {
        r->hi = a;
        r->lo = 0xFFFFFFFFu;
    }
    else
    {
        r->hi = a % b;
        r->lo = a / b;
    }
}
static inline void Rc_Mult(RcRegs* r, unsigned int a, unsigned int b)
{
    long long p = (long long)(int)a * (int)b;
    r->lo = (unsigned int)p;
    r->hi = (unsigned int)((unsigned long long)p >> 32);
}
static inline void Rc_Multu(RcRegs* r, unsigned int a, unsigned int b)
{
    unsigned long long p = (unsigned long long)a * b;
    r->lo = (unsigned int)p;
    r->hi = (unsigned int)(p >> 32);
}

/* Debugging (SH1_WATCH_PACKET=1): every wrapped recompiled function checks that it doesn't move
 * GsOUT_PACKET_P out of the PS1 RAM area (src/port/ps2/crash_ps2.c: Port_WatchBegin/End). */
#ifdef SH_PORT_WATCH_PACKET
unsigned int Port_WatchBegin(void);
void         Port_WatchEnd(unsigned int before, const char* name, unsigned int a0, unsigned int a1, unsigned int a2,
                           unsigned int a3, unsigned int ret);
#define RC_WATCH_BEGIN unsigned int rcWatchBefore = Port_WatchBegin();
#define RC_WATCH_END(name, a0, a1, a2, a3, ret) Port_WatchEnd(rcWatchBefore, name, a0, a1, a2, a3, ret);
#else
#define RC_WATCH_BEGIN
#define RC_WATCH_END(name, a0, a1, a2, a3, ret)
#endif

#endif
